### ISSUE TITLE
Expected object missing in `octreeResults` array when using `useVertices: true`

### ISSUE THREAD

**Issue by Wilt** [collinhover/threeoctree#14]
_I know you are very busy @collinhover but I hope you could be so kind to shortly look into this issue._

Prior to making a PR for the other issue that I posted (about optional parameter for sorting objects, which is actually an easy fix), I was working with your Octree library to wrap my head around it.

I had some serious issues with the octree search results inside my project when setting `useVertices` to `true`. To isolate the issue and to make sure the issue wasn't caused by my own code I made a fiddle in which I was able to reproduce this issue.

https://jsfiddle.net/wilt/8jeu2ykg/

When hovering with the mouse on the beam at the location of the white arrow in the screenshot below, the diagonal beam is missing from the `octreeResults` set. I could work on a PR for this, but I actually have no idea what is causing this issue. Can you give some guidance on where to look for the problem for this specific case?
The funny thing is when setting `useVertices` to `false` (line 138 in the fiddle) all is fine; in that case the beam is in the result set as expected...

![image](https://cloud.githubusercontent.com/assets/2419627/17593004/b5affad2-5fe4-11e6-80c1-e5a4e383141d.png)

Note: In my fiddle I implemented the sort method in this example very simply with array sort method:
````
intersects.sort(function(a, b) {
    return a.distance - b.distance;
});
````
But this cannot be causing the issue, since the actual `diagonal` beam is already missing in the `octreeResult` set (see also the output in the console)...

**Comment by collinhover** [comment]
If you set `useVertices` to true, the object gets added not by its faces but by its vertices. I'm guessing here because I'm at least a year behind on THREEJS architecture, but I think the issue is that when the object is added by its vertices, it isn't calculating its properties correctly.

I'd start by adding breakpoints in the following places:

* Check if the radius of the octree object is correct when using vertices: https://github.com/collinhover/threeoctree/blob/master/threeoctree.js#L728

* Check if the octant index of the octree object is correct:
https://github.com/collinhover/threeoctree/blob/master/threeoctree.js#L991

* Simplify your scene if possible, determine what octree node the object should be in, then when you do a search that intersects that octree node, check that node's list of objects: https://github.com/collinhover/threeoctree/blob/master/threeoctree.js#L1930

Let me know what you find.

**Comment by Wilt** [comment]
It seems the issue is caused by this line: https://github.com/collinhover/threeoctree/blob/master/threeoctree.js#L728

The radius for vertices is always 1.
When we have a huge object like the diagonal beam there are 8 vertices that are added to the octree,  4 vertices from the top and 4 from the bottom of the diagonal beam all with a radius of 1. 
As a result the beam is not present in the octant where the arrow is pointing, while it should be. Changing the code for the radius similar to the code for adding an object (https://github.com/collinhover/threeoctree/blob/master/threeoctree.js#L741) solves the issue:

    if (this.object.geometry.boundingSphere === null) {
        this.object.geometry.computeBoundingSphere();
    }
    this.radius = this.object.geometry.boundingSphere.radius;

instead of:

    this.radius = this.object.material.size || 1;

It seems to solve the problem...

If you agree on this solution I can make a PR for this change...

**Comment by collinhover** [comment]
That seems reasonable. Go for it :)

**Comment by Wilt** [comment]
Wow, that was fast :smile:
Great! :+1: 
Will let you know as soon as I found time to do this...

**Comment by Wilt** [comment]
PR here: https://github.com/collinhover/threeoctree/pull/16
